version: 2
updates:
  # Atualizar dependências npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    # reviewers:
    #   - "seu-usuario-github" # Substitua pelo seu username
    # assignees:
    #   - "seu-usuario-github" # Substitua pelo seu username

  # Atualizar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "ci"
      - "automated"
    commit-message:
      prefix: "ci"

  # Atualizar Docker
  - package-ecosystem: "docker"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "docker"
      - "automated"

  - package-ecosystem: "docker"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "docker"
      - "automated"

