# Railway Configuration File
# Documentação: https://docs.railway.app/reference/config-file

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

# Variáveis de ambiente (configure no Dashboard)
# PORT = 4000
# NODE_ENV = production
# DATABASE_URL = postgresql://...
# CORS_ORIGINS = https://seu-frontend.netlify.app

